name: Busipool

on:
  pull_requests:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    containers:
      images: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test
      - run: npm run build
